[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mistral-pdf-ocr"
version = "0.1.0"
description = "Mistral PDF OCR MCP Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
    "mistralai @ git+https://github.com/mistralai/client-python.git",
    "PyPDF2>=3.0.0",
    "python-dotenv>=1.0.0"
]

[project.optional-dependencies]
gui = ["nicegui>=1.4.0"]
cli = ["click>=8.0.0"]

[project.scripts]
mistral-pdf-ocr = "mistral_pdf_ocr.mistral_mcp_server:main_sync"
mistral-pdf-ocr-cli = "mistral_pdf_ocr.mistral_cl:main"
mistral-pdf-ocr-gui = "mistral_pdf_ocr.mistral_gui:main"

[tool.hatch.metadata]
allow-direct-references = true
